spring:
  application:
    name: cloud-eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
        defaultZone: http://euk01:7900/eureka,http://euk02:7901/eureka,http://euk03:7902/eureka
  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0.85
    eviction-interval-timer-in-ms: 1000
    use-read-only-response-cache: true
    response-cache-update-interval-ms: 1000

---
server:
  port: 7900
eureka:
  instance:
    hostname: euk01
spring:
  config:
    activate:
      on-profile: 7900
---
server:
  port: 7901
eureka:
  instance:
    hostname: euk02
spring:
  config:
    activate:
      on-profile: 7901
---
server:
  port: 7902
eureka:
  instance:
    hostname: euk03
spring:
  config:
    activate:
      on-profile: 7902